### ISSUE TITLE
Create a github action to pushlish on tagged commits to master 

### ISSUE THREAD

**Issue by blester125** [dpressel/mead-baseline#434]
[example here](https://github.com/blester125/text-rank/blob/master/.github/workflows/publish.yml)

**Comment by dpressel** [comment]
I think this makes more sense to do in mead GPU where we are cutting releases for docker anyway

**Comment by dpressel** [comment]
Its a bit more complicated than the example since it clone sub-modules and builds 2 packages with wheels.  One thing -- I wasnt able to use the submodule action -- followed info on this ticket to fix:
https://github.com/textbook/git-checkout-submodule-action/issues/2

https://github.com/mead-ml/mead-gpu/blob/master/.github/workflows/pypi.yml

might want to add xpctl?
